### ISSUE TITLE
期待集成到PhalApi扩展类库

### ISSUE THREAD

**Issue by phalapi** [wulongtao/think-wxminihelper#1]
@wulongtao 您好，

[PhalApi](https://github.com/phalapi/phalapi)是一个开源接口框架，官网请见：[https://www.phalapi.net/](https://www.phalapi.net/)。最近有PhalApi开发同学希望可以支持微信小程序开发，并且推荐了您这个项目作为参考。我们发现，这是一个很棒的项目！实现了微信小程序登录过程。  

请问：  

 + 1、可以也把这个项目修改成适合PhalApi框架的扩展类库，并添加到[PhalApi-Library](
http://git.oschina.net/dogstar/PhalApi-Library)吗？方便更多的PhalApi开发同学可以使用。   

在PhalApi中，获取参数，可以使用：  
```
// $code = input("code", '', 'htmlspecialchars_decode');
$code = htmlspecialchars_decode(DI()->get("code"));
```
配置的读取，可以使用：  
```
// if ($wx = Config::get('wx')) {
if ($wx = DI()->config->get('wx')) {
```

PhalApi的使用，以及其扩展类库的开发都是相当简单的，更多可参考[在线文档](https://www.phalapi.net/wikis/)。

 + 2、如果您时间不允许，是否可以允许我们将此项目进行二次开发，修改并添加到PhalApi框架的扩展类库？在代码中，我们会保留原来的版权信息，以及注明项目出处。  

如有问题，可随时与我们联系，谢谢！

**Comment by wulongtao** [comment]
可以啊，不过也请加上原作者注释吧

**Comment by phalapi** [comment]
@wulongtao 是您来开发，还是我们来开发？

**Comment by wulongtao** [comment]
你们来开发吧，时间确实不允许，不好意思啊.....

**Comment by phalapi** [comment]
好的，非常感谢！如果有不懂，再来请教。  

集成到PhalApi扩展的项目位置为：[WechatMini](https://github.com/phalapi/phalapi-library/tree/master/WechatMini)
